# Generated by Django 5.0.1 on 2024-01-11 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
    ]
